const { chromium } = require('C:/Users/avira/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const output = path.join(__dirname, 'review');
fs.mkdirSync(output, {recursive:true});
(async()=>{
 const browser = await chromium.launch({headless:true,channel:'msedge'});
 const page = await browser.newPage({viewport:{width:1440,height:1040}, deviceScaleFactor:1});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 const url=pathToFileURL(path.join(__dirname,'index.html')).href;
 await page.goto(url);
 await page.waitForTimeout(300);
 await page.screenshot({path:path.join(output,'01-hub-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(output,'02-hub-phone.png'),fullPage:true});
 await page.screenshot({path:path.join(output,'hub-phone-viewport.png')});
 const views=['hub','connect','chat','notes','packs','settings','diagnostics','sos'];
 const overflows=[];
 for(const width of [1440,820,720,390,360,320]){
  await page.setViewportSize({width,height:844});
  for(const view of views){
   await page.goto(url+'#'+view);
   await page.waitForTimeout(280);
   const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
   if(overflow) overflows.push({width,view});
   if(width===390) await page.screenshot({path:path.join(output,view+'-phone.png'),fullPage:true});
  }
 }
 assert.deepEqual(overflows,[],'Horizontal overflow');
 const passed=[];
 await page.setViewportSize({width:390,height:844});
 await page.goto(url+'#hub');
 await page.waitForTimeout(300);
 async function screen(name){await page.evaluate(n=>location.hash=n,name);await page.waitForFunction(n=>location.hash==='#'+n,name);await page.waitForTimeout(300);}
 // Hold-to-talk generates only a sample transcript, and saves it separately.
 await page.locator('.talk-panel [data-ptt]').focus();
 await page.keyboard.down('Space');await page.waitForTimeout(350);await page.keyboard.up('Space');
 await page.waitForTimeout(1000);
 await screen('notes');
 assert.equal(await page.locator('.note-card').count(),8);
 await page.locator('[data-action="delete-note"]').first().click();
 await page.getByRole('button',{name:'Keep note',exact:true}).click();
 assert.equal(await page.locator('.note-card').count(),8);
 await page.locator('[data-action="delete-note"]').first().click();
 await page.getByRole('button',{name:'Delete note',exact:true}).click();
 assert.equal(await page.locator('.note-card').count(),7);
 await screen('chat');
 assert.ok(await page.locator('.conversation-row').count() >= 2);
 await page.locator('.conversation-row[data-peer-id="aarav-bt"]').click();
 assert.equal(await page.locator('.bubble-wrap').count(),4);
 passed.push('PTT transcript; delete cancel/confirm; sent messages preserved');
 // Text input is escaped; it never becomes markup.
 await page.locator('#chat-input').fill('<img src=x onerror=alert(1)>');
 await page.getByRole('button',{name:'Send message',exact:true}).click();
 assert.equal(await page.locator('.bubble img').count(),0);
 assert.equal(await page.locator('.bubble-wrap').count(),5);
 passed.push('Typed message and escaped content');
 await page.selectOption('#scenario','disconnected');await screen('connect');
 await page.getByRole('button',{name:'Discover Bluetooth devices',exact:true}).click();
 await page.locator('[data-peer="aarav-bt"] [data-action="pair"]').waitFor();
 await page.locator('[data-peer="aarav-bt"] [data-action="pair"]').click();
 await page.getByRole('button',{name:'Codes differ',exact:true}).click();
 await page.locator('[data-peer="aarav-bt"] [data-action="pair"]').click();
 await page.getByRole('button',{name:'Codes match',exact:true}).click();
 assert.ok((await page.locator('.connection-overview').innerText()).includes('Verified'));
 passed.push('Discovery; reject mismatched code; verify peer');
 await screen('hub');await page.locator('[data-action="retry"]').first().click();
 await page.getByRole('button',{name:'Failed',exact:true}).click();
 assert.equal(await page.getByText('No failed messages in this preview.',{exact:true}).count(),1);
 passed.push('Retry delivery and message filter');
 await page.selectOption('#scenario','missing');
 await page.locator('.talk-panel [data-ptt]').click();
 await page.locator('[data-pack="hi"] [data-action="download"]').click();
 await page.locator('[data-pack="hi"] [data-action="cancel-download"]').click();
 await page.locator('[data-pack="hi"] [data-action="download"]').click();
 await page.locator('[data-pack="hi"] [data-action="active-mic"]').waitFor();
 await page.selectOption('#scenario','download-failed');
 await page.locator('[data-pack="ta"] [data-action="download"]').click();
 await page.locator('[data-pack="ta"] [data-action="active-mic"]').waitFor();
 await page.locator('[data-pack="ta"] [data-action="active-mic"]').click();
 await screen('hub');
 assert.ok((await page.locator('.lang-select').first().innerText()).includes('தமிழ்'));
 await page.locator('.talk-panel [data-ptt]').focus();await page.keyboard.down('Space');await page.waitForTimeout(300);await page.keyboard.up('Space');await page.waitForTimeout(1000);
 await screen('notes');assert.ok((await page.locator('.note-card').first().innerText()).includes('நான்'));
 passed.push('Missing model; cancel download; retry failed download; native-script sample');
 await screen('sos');await page.locator('[data-value="Medical SOS"]').click();
 await page.getByRole('button',{name:'Send alert',exact:true}).click();
 await page.getByRole('heading',{name:'Sending sample alert…',exact:true}).waitFor();
 await page.getByRole('heading',{name:'Delivered to peer device',exact:true}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'Delivered to peer device',exact:true}).count(),1);
 await page.getByRole('button',{name:'Preview human ACK',exact:true}).click();
 assert.equal(await page.getByRole('heading',{name:'Aarav acknowledged',exact:true}).count(),1);
 await page.getByRole('button',{name:'Done',exact:true}).click();
 passed.push('SOS confirmation; device delivery separated from human acknowledgement');
 await screen('settings');await page.getByRole('button',{name:'Edit',exact:true}).click();
 await page.locator('[name="operator"]').fill('Test User');await page.getByRole('button',{name:'Save name',exact:true}).click();
 assert.equal(await page.getByRole('heading',{name:'Test User',exact:true}).count(),1);
 await page.getByRole('button',{name:'Wipe local data',exact:true}).click();
 await page.locator('#hold-wipe').focus();await page.keyboard.down('Space');await page.waitForTimeout(350);await page.keyboard.up('Space');
 assert.equal(await page.locator('dialog[open]').count(),1,'Short hold must not wipe');
 await page.locator('#hold-wipe').focus();await page.keyboard.down('Space');await page.waitForTimeout(2200);await page.keyboard.up('Space');
 await screen('notes');assert.equal(await page.locator('.note-card').count(),0);
 await screen('packs');assert.equal(await page.locator('[data-action="active-mic"]').count(),3);
 passed.push('Profile edit; hold-to-wipe duration; model packs retained');
 // Bucketing uses device calendar days, with year included for older notes.
 const groups=await page.evaluate(()=>{const f=window.itantraPreview.bucket,now=new Date(2026,8,30,12);return [0,1,6,10].map(d=>f(new Date(2026,8,30-d,9).getTime(),now)).concat([f(new Date(2026,7,12).getTime(),now),f(new Date(2025,7,12).getTime(),now)]);});
 assert.deepEqual(groups,['Today','Yesterday','This week','This month','Older · August 2026','Older · August 2025']);
 passed.push('Date buckets: today, yesterday, 6/10 days, previous month, 13 months');
 await page.emulateMedia({reducedMotion:'reduce'});
 await screen('hub');
 assert.equal(await page.locator('main').evaluate(el=>getComputedStyle(el).animationName),'none');
 passed.push('Reduced motion');
 // Touch gesture and fixed microphone dock are distinct from the keyboard path.
 await page.selectOption('#scenario','connected');
 const mic=page.locator('.talk-panel [data-ptt]');
 const r=await mic.boundingBox();
 await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();
 await page.waitForTimeout(300);await page.mouse.move(r.x+r.width/2,r.y+r.height/2-85);await page.mouse.up();
 assert.equal(await page.getByRole('button',{name:'Finish recording',exact:true}).count(),1);
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 assert.equal(await page.locator('.ptt.recording').count(),0);
 await page.getByRole('button',{name:'Hands-free',exact:true}).click();
 await page.locator('.talk-panel [data-ptt]').click();await page.waitForTimeout(300);
 assert.equal(await page.locator('.talk-panel .ptt.recording').count(),1);
 await page.locator('.talk-panel [data-ptt]').click();await page.waitForTimeout(1000);
 // The compact phone hub can keep its mic in view even at max scroll. Add test-only
 // scroll room to exercise the dock's "mic has gone above the viewport" state.
 await page.evaluate(()=>{document.querySelector('#main').style.minHeight='1600px';window.scrollTo(0,document.body.scrollHeight)});
 await page.locator('#talk-dock.visible').waitFor();
 await page.evaluate(()=>{document.querySelector('#main').style.minHeight='';window.scrollTo(0,0)});
 passed.push('Pointer slide-to-lock/cancel; hands-free start/pause; fixed talk dock');
 await page.setViewportSize({width:320,height:740});
 await screen('hub');await page.locator('[data-kind="target"]').click();
 const dialogOverflow=await page.locator('dialog').evaluate(el=>el.scrollWidth>el.clientWidth);
 assert.equal(dialogOverflow,false,'Language dialog overflow at 320 px');
 await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 await page.selectOption('#scenario','disconnected');await screen('sos');
 await page.locator('[data-value="Need help"]').click();
 assert.equal(await page.getByRole('heading',{name:'Connect a peer first',exact:true}).count(),1);
 await page.keyboard.press('Escape');
 passed.push('Narrow modal layout; Escape dismissal; disconnected SOS blocks sending');
 assert.deepEqual(errors,[],'Browser errors');
 await browser.close();
 const report={screens:views.length,widths:[1440,820,720,390,360,320],overflows,errors,passed,output};
 fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
